commerce:
  items:
    1000: "Nike","Just Do It.","shoes",20
    1001: "Reebok","Run Fast. Go Far.","shoes",21
    1002: "Adidas","All Day I Dream About Sports","shoes",22
    1003: "New Balance","Run like you mean it.","shoes",23
    1004: "Clarks","Always be walking in amazing comfort.","shoes",24
    1005: "Puma","Meow. This cat wins by stealth.","shoes",25
    1006: "Sketchers","Tragically hip, very nice, everyone likes.","shoes",26
    1007: "Uggs","Dead animal, inside out.","shoes",27
    1008: "Dockers","Pants that should look more expensive than they are, but don't.","pants",28
    1009: "Levis","Ruff. Tuff. Bloo. Everyone wants one.","pants",29
    1010: "Wrangler","I could be Levis, but I think I will be ok like this too.","pants",201
    1011: "Gap","So smart you will wear many.","pants",202
    1012: "Khakis","Look like you know what you are doing.","pants",203
    1013: "Chinos","Also look like you know what you're doing, mostly.","pants",204
    1014: "Woosters","Look awesome in these things, they have wings and flaps.","pants",205
    1015: "Gorgons","You will marry your lover.","pants",206
    1016: "Scoobys","Don't be scared to take the leap with these on.","pants",207
    1017: "Arbo","This will come untucked a lot, because good.","shirt",208
    1018: "Perdan","Its not a very good name, but it sells a lot.","shirt",209
    1019: "Hertzog","Some crazy dude made this shirt. We are still selling them.","shirt",200
    1020: "Braunfalter","You can make your own happiness with thing on.","shirt",30
    1021: "Drebens","The greatest risk is not taking one.","shirt",40
    1022: "Jesters","All the fun you can have with clothes on.","shirt",50
    1023: "Blue Rips","Very blue, very nice, wear everywhere.","shirt",60
    1024: "Vertal","Big, tall, and everything else also.","shirt",70
    1025: "Pulman","A great shirt, built to take the travel you can give it.","shirt",80
    1026: "Shirtly","Try one and it will keep showing up in the mail.","shirt",90
    1027: "Burberry","Very wrap, but you will have an empty pocket.","knits",301
    1028: "Mulberry","Wealth awaits you very soon.","knits",302
    1029: "Jumberry","If you feel you are right, stand firmly by your convictions.","knits",303
    1030: "Gumberry","If winter comes, can spring be far behind?","knits",304
    1031: "Plaidonic","Keep your eye out for someone special.","knits",305
    1032: "Weavers","You are very talented in many ways.","knits",306
    1033: "Loomster","A stranger, is a friend you have not spoken to yet.","knits",307
    1034: "Yarnery","A new voyage will fill your life with untold memories.","knits",308
    1035: "Microtech","You will travel to many exotic places in your lifetime.","knits",401
    1036: "Stitchers","Your ability for accomplishment will follow with success.","knits",402
    1037: "Trunks","Nothing astonishes men so much as common sense and plain dealing.","beach",403
    1038: "Divers","Its amazing how much good you can do if you dont care who gets the credit.","beach",404
    1039: "BigReds","Everyone agrees. You are the best.","beach",405
    1040: "SunSand","LIFE CONSIST NOT IN HOLDING GOOD CARDS, BUT IN PLAYING THOSE YOU HOLD WELL.","beach",406
    1041: "SurfLogic","Jealousy doesn't open doors, it closes them!","beach",407
    1042: "Sandcastle","It's better to be alone sometimes.","beach",408
    1043: "Coral","When fear hurts you, conquer it and defeat it!","beach",409
    1044: "Palman","Let the deeds speak.","beach",410
    1045: "Harvard","The original preppy look.","sport",420
    1046: "Yale","Preppy, and without apology.","sport",430
    1047: "Columbia","Modern, urban, sleek, classy without being stuffy.","sport",520
    1048: "Penn","Easygoing, fun, good for all occasions.","sport",620
    1049: "Princeton","You either have it or you don't.","sport",720
